name: Release and Build Service Images

on:
  workflow_dispatch:

jobs:
  get_tag:
    name: Get latest git tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Extract latest tag
        id: tag
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

  build_backend:
    name: Build and Publish Backend Docker image
    needs: get_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Build backend container image
        run: |
          docker build \
            -t ${{ secrets.REGISTRY_NAME }}/open-wearables-backend:${{ needs.get_tag.outputs.version }} \
            ./backend
      - name: Push backend image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/open-wearables-backend:${{ needs.get_tag.outputs.version }}

  build_frontend:
    name: Build and Publish Frontend Docker image
    needs: get_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200
      - name: Build frontend container image
        run: |
          docker build \
            -t ${{ secrets.REGISTRY_NAME }}/open-wearables-frontend:${{ needs.get_tag.outputs.version }} \
            ./frontend
      - name: Push frontend image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/open-wearables-frontend:${{ needs.get_tag.outputs.version }}
